### ISSUE TITLE
"Check low breathability" fix crashes the game

### ISSUE THREAD

**Issue by wilki24** [llunak/oni-fixesandtweaks#1]
The linked issue was marked as fixed by Klei, so this particular fix may not be needed any longer.

[04:07:22.612] [1] [INFO] Fixes and Tweaks's patched_method BreathabilityTracker.UpdateData matched in the stack trace, adding to referenced mods list
  [DebugConsole][1]: Error[Exception]: NullReferenceException: Object reference not set to an instance of an object
FixesAndTweaks.BreathabilityTracker_Patch.UpdateData_Hook (OxygenBreather component) (at <5761e4248cf3432795615a8e3c7d1e23>:0)
(wrapper dynamic-method) BreathabilityTracker.BreathabilityTracker.UpdateData_Patch0(BreathabilityTracker)
TrackerTool.Update () (at <990b4cf9a7d84305ad7eaef1059b672b>:0)

**Comment by llunak** [comment]
Already handled, thank you.
