### ISSUE TITLE
error in latest fix to `Drowning.cs`: `x` rather than `y` used in inner loop.

### ISSUE THREAD

**Issue by slippycheeze** [llunak/oni-fixesandtweaks#2]
I was looking at the latest release of "Fixes and Tweaks", and I suspect I see a bug in the code.
I think that line 40 of Drowning.cs is incorrectly using x rather than y in the for loop:

```C#
for( int x = cavity.minX; x <= cavity.maxX; ++x )
    // x rather than y here: ↓↓↓↓↓
    for( int y = cavity.minY; x <= cavity.maxY; ++x )
        { … }
```

it shouldn't infloop, just walk weirdly and terminate much earlier than I think was intended?

**Comment by llunak** [comment]
You're right, thank you.
